### ISSUE TITLE
Order Tracking Page needs more information!

### ISSUE THREAD

**Issue by tareq89** [NerdCats/WebCat#96]
Background:

Right now, order tracking page provide information on:

- Pickup Address
- Delivery Address
- Order Status
- Map
- Product Details

Along with that, some more information are needed to be provided. They are:

- Payment Status
- Pickup delivery start time, end time
- In case of special delivery, cash receive time, cash payment time

**Comment by tareq89** [comment]
@nabilrhman, please provide the designs of the extra fields I requested!

**Comment by tonmoy71** [comment]
This issue depends on TaskCat Release 2

**Comment by thehoneymad** [comment]
Um... this is okay as far as it goes.

I have concerns over two things here.

1. The orderInfo class parses data through an if else which would soon fail if there's a different job type comes with more steps. I personally discourage these lines because that limits the code from doing much as this would be refactored later and more and more if else would come up essentially making it a blackbox in the process.

2. Comments in the code: If you don't need a piece of code, just delete it. Keeping commented markups hurts readability. 

Tips:

1. Making a info page out of a job itself is pretty easy, all you have to do is sanitize job type and job task type names and the job task states in a loop.
